### ISSUE TITLE
Update purgecss dependencies? Blocklist required

### ISSUE THREAD

**Issue by dloop-mb** [Developmint/nuxt-purgecss#108]
Is there a plan for updating the purgecss (purgecss+postcss+webpack) dependencies? At least to version 3? Or at least could it be possible to set up a branch like renovate/all-major-patch?
It would be nice to use the "blocklist" option with Nuxt.

**Comment by xeno** [comment]
This project is looking pretty dead, unfortunately. :(

**Comment by manniL** [comment]
Resolved ☺️
