### ISSUE TITLE
::v-deep code disappear

### ISSUE THREAD

**Issue by vvvhung** [Developmint/nuxt-purgecss#122]
My ::v-deep code to style the child things was purged. Is there any solution to prevent that?

**Comment by manniL** [comment]
Yes - probably whitelisting the selector. ☺️

**Comment by vvvhung** [comment]
I tried without success. It did not work with static generating. This is the rendered html node:

`<div class="w-full flex flex-col gap-2 mt-3 card-hoder-name" data-v-1994621e="" style="">
    <label class="text-sm" data-v-1994621e="">Name (as appears on your card)</label> 
    <span class="w-full" data-v-1994621e="">
        <span type="text" msg-class="bg-red-700 text-white z-10 rounded-sm px-2" value="" class="w-full" data-v-5c0abf1e="" data-v-1994621e="">
            <div class="input-wrapper touched pristine invalid validated required failed" data-v-5c0abf1e="">
                <input msg-class="bg-red-700 text-white z-10 rounded-sm px-2" class="w-full" data-v-5c0abf1e="" type="text">
            </div>
        </span>
    </span>
</div>`

And this is the scss:
`::v-deep .card-hoder-name {
  .input-wrapper {
    border: 1px solid #6d64a4;
    position: relative;
    background: #494184;

    input {
      background-color: #352a7a00 !important;
      color: #ffffff !important;
    }
  }
}`

I tried whitelisting like this: 
`purgeCSS: {
    // your settings here
    whitelist: ['.card-hoder-name', 'card-hoder-name'],
  },`

**Comment by manniL** [comment]
Try adding `::v-deep` as regex to the whitelist.

like: `whitelist: [/::v-deep.*/]`

**Comment by vvvhung** [comment]
still no luck

**Comment by manniL** [comment]
In case these won't work, please try https://purgecss.com/safelisting.html#in-the-css-directly

If that doesn't work either, could you provide a minimal reproduction?
Happy to reopen the issue then

**Comment by vvvhung** [comment]
Still no luck. I created this repo as a minimal reproduction: https://github.com/vvvhung/purgecss-vdeep

**Comment by manniL** [comment]
Could you try:

```js
purgeCSS: {
    whitelistPatterns: [/::v-deep.*/]
  }
```

**Comment by manniL** [comment]
PS: if you want to see support of the latest PurgeCSS version for Nuxt2 too, then please vote on #127 ☺️

**Comment by vvvhung** [comment]
Yeah, it works. Thanks. 
Sure.
