### ISSUE TITLE
[BREAKING] set postcss mode as default

### ISSUE THREAD

**Issue by manniL** [Developmint/nuxt-purgecss#15]

**Comment by riveraeu** [comment]
Hey is this why I am seeing the following error message when I generate my static site?

` ERROR  Webpack mode only works with build.extractCSS set to *true*. Either extract your CSS or use 'postcss' mode   `

**Comment by manniL** [comment]
The error is pretty self-descriptive.

Either use `build.extractCSS: true` or the postcss mode.

Examples are in `tests/fixtures`

**Comment by willdante** [comment]
Hi,

As explained in the issue #46, I've made several tests because I've had scroll issues when using the module.

Webpack mode with Extract CSS was causing scroll issues for me and I've solved it by using postcss mode.

So I guess it's should definitively be the default mode ;)

**Comment by bjesus** [comment]
Can someone please give a one/two sentences explanation about the pros and cons of postcss vs extractCSS? I understand that I can choose between the two but have no idea which one is better for me. why would one pick one over the other? does it matter?

**Comment by manniL** [comment]
Resolved

**Comment by manniL** [comment]
> Can someone please give a one/two sentences explanation about the pros and cons of postcss vs extractCSS? I understand that I can choose between the two but have no idea which one is better for me. why would one pick one over the other? does it matter?

Usually you want to use it with `postcss`. Otherwise, your CSS is extracted in different files (not included in the component files). This *can* be useful if you have e.g. only global CSS.
