### ISSUE TITLE
bootstrap-vuew will purged

### ISSUE THREAD

**Issue by derevandal** [Developmint/nuxt-purgecss#22]
Hi,
I'm trying to use purgecss with bootstrap-vue... I read about this in several related issues, but, I can not be successful.

```js
  purgeCSS: {
    mode: 'postcss',
    paths: [
      'components/**/*.vue',
      'layouts/**/*.vue',
      'pages/**/*.vue',
      'plugins/**/*.js',
      'node_modules/bootstrap-vue/es/**/**/*.js',
      'node_modules/bootstrap-vue/**/*.js'
    ],
    styleExtensions: ['.css'],
    whitelist: ['body', 'html', 'nuxt-progress', 'navbar'],
    whitelistPatterns: [/^b-/, /nav/]
  },

  build: {
    extractCSS: true,
    ...
  }
```
`index.vue`
```vue
<template>
  <div>
    <b-navbar
      toggleable="md"
      type="dark"
      variant="info">

      <b-navbar-toggle target="nav_collapse"/>

      <b-navbar-brand href="#">NavBar</b-navbar-brand>

      <b-collapse
        id="nav_collapse"
        is-nav>

        <b-navbar-nav>
          <b-nav-item href="#">Link</b-nav-item>
          <b-nav-item
            href="#"
            disabled>Disabled</b-nav-item>
        </b-navbar-nav>

        <!-- Right aligned nav items -->
        <b-navbar-nav class="ml-auto">

          <b-nav-form>
            <b-form-input
              size="sm"
              class="mr-sm-2"
              type="text"
              placeholder="Search"/>
            <b-button
              size="sm"
              class="my-2 my-sm-0"
              type="submit">Search</b-button>
          </b-nav-form>

          <b-nav-item-dropdown
            text="Lang"
            right>
            <b-dropdown-item href="#">EN</b-dropdown-item>
            <b-dropdown-item href="#">ES</b-dropdown-item>
            <b-dropdown-item href="#">RU</b-dropdown-item>
            <b-dropdown-item href="#">FA</b-dropdown-item>
          </b-nav-item-dropdown>

          <b-nav-item-dropdown right>
            <!-- Using button-content slot -->
            <template slot="button-content">
              <em>User</em>
            </template>
            <b-dropdown-item href="#">Profile</b-dropdown-item>
            <b-dropdown-item href="#">Signout</b-dropdown-item>
          </b-nav-item-dropdown>
        </b-navbar-nav>

      </b-collapse>
    </b-navbar>
  </div>
</template>
```
#14 #5 [lichter](https://github.com/manniL/lichter.io/blob/master/nuxt.config.js#L26)

could anyone help me?

thanks.

**Comment by manniL** [comment]
This is a bit more complicated with 3rd party libs. PurgeCSS scans your files for text, it does not evaluate JS or Vue at any point. As you don't use classes (bc they are inside the components and those aren't in your `paths`) bootstrap will be completely purged.

You can either:

* Add the path of the used components to the `paths` array
* Whitelist the classes used
* Use an external bootstrap (S)CSS and remove the unused parts on your own.

The last option might be the best for you use case. :|

**Comment by derevandal** [comment]
I understood. Thanks.
I'll use SCSS :|

**Comment by zakkor** [comment]
Also bumped into a similar issue, just for clarification, you said: "Add the path of the used components to the paths array" - does that mean that something like this would let purgecss pick up class names from external single file components? 

```
paths: [
      'node_modules/some-library/components/*.vue'
] 
```

**Comment by manniL** [comment]
@zakkor In theory yes. Haven't tried that though.

**Comment by zakkor** [comment]
Unfortunately, it doesn't seem to work :(
I'll try to provide a minimal reproducible repo soon

**Comment by bart** [comment]
Any update on this? I have the same problem with element ui in a nuxtJS project

**Comment by Epistol** [comment]
Bump, still nothing ?

**Comment by bart** [comment]
I'm using tailwindcss instead of bootstrap now.

**Comment by Epistol** [comment]
Cool but for a project that i can't switch to tailwind yet, I'd wish to knew if it was possible to get a way to avoid purgecss to wipe out any third party library

**Comment by bart** [comment]
Maybe the purgecss-whitelister plugin (https://github.com/qodesmith/purgecss-whitelister) could guide you into the right direction?

**Comment by CurtisBelt** [comment]
@Epistol @bart are you guys talking about the `whitelistPatterns` option?

From my nuxt.config.js I have this in a project:

```js
  purgeCSS: {
    mode: 'postcss',
    whitelistPatterns: [
      /^fa\-/,
      /\-\-fa$/,
      /^js\-is/,
      /^js\-stickybit/,
      /^flickity\-/
    ]
  },
```
You can do this out of the box with nuxt-purgecss

**Comment by mwc2016** [comment]
Go to bootstrap.scss and put these line 

Example
```
/*! purgecss start ignore */
@import "dropdown";
/*! purgecss end ignore */
```

**Comment by Mauricioft** [comment]
I had the same problem with bootstrap-vue, this was my configuration, I had to whitelist the classes that needed not to be excluded. Keep in mind that you must add to the safelist the classes that you do not want to be purged. I hope it can serve you

``
{
              '@fullhuman/postcss-purgecss': {
                content: [
                  'components / ** / *. vue',
                  'layouts / ** / *. vue',
                  'pages / ** / *. vue',
                ],
                safelist: [
                  / - (leave | enter | appear) (| - (to | from | active)) $ /,
                  / ^ nuxt-link (| -exact) -active $ /,
                  /^(?!cursor-move).+-move$/,
                  /data-v-.*/,
                  /(container).*/,
                  /(nav).*/,
                  /(bg).*/,
                  /(btn).*/,
                  /^(row).*/,
                  /^(tooltip).*/,
                  /^(col).*/,
                  /(text).*/,
                  /(border).*/,
                  / fieldset /,
                  /^(navbar).*/,
                  /^(class*=col-).*/,
                  /^(form-row).*/,
                  /^(modal).*/,
                  /^offset-.*/,
                ],
                extractors: [
                  {
                    extractor: content => {
                      const contentWithoutStyleBlocks = content.replace (/ <style [^] +? <\ / style> / gi, '')
                      return contentWithoutStyleBlocks.match (/ [\ w-.:/íritu+(?<!:)/g) || []
                    },
                    extensions: ['html', 'vue', 'js']
                  }
                ]
              }
            }
``
