### ISSUE TITLE
DX: Warn when module when was disabled by being in dev mode

### ISSUE THREAD

**Issue by studnitz** [Developmint/nuxt-purgecss#23]
Hi,

really like the module so far! I also like the many error and warn messages it does provide, but as the title suggests I have an idea for one more.

The warn message could be something like:

Module was not enabled, because you are currently in development mode.

Maybe I could also tackle this myself, but I think a new flag would have to be introduced to check if the module was disabled automatically or explicitly by the user.

Cheers

**Comment by manniL** [comment]
:+1: For that :relaxed: 

You can probably do that by checking the user nuxt.config.js value for `enabled` (if there is any custom fn or not :relaxed:)
