### ISSUE TITLE
Can I see the differences between my old and my optimized css?

### ISSUE THREAD

**Issue by ChucKN0risK** [Developmint/nuxt-purgecss#32]
I installed and used the plugin correctly but I can't manage to see if it works correctly.
Does anyone have a solution for me?

**Comment by manniL** [comment]
Hey 👋 

A simple example (for an existing nuxt project):

1. Create a global CSS file (say `app.css`) and add it to your nuxt config
2. Create a CSS class `.unused` and give it any properties you like.
3. Create a CSS class `.used` and use it in your `index.vue`
4. Add the `nuxt-purgecss` module and set the correct mode (webpack/postcss)
5. Build and start the nuxt app
6. go to *any* page and look for `.unused` in the source code.
7. Assert that `.unused` is not present

**Comment by florinesueur** [comment]
Hello @manniL,

To resume your example, if I create `.unused` in my `index.vue`.
The plugin don't work `.unused` is present.

**Comment by manniL** [comment]
@florinesueur That's correct.

Because `purgecss` will scan all your `.vue` files, it'll find the CSS you wrote there and hence will not delete it.

If you'd add the class to your global CSS, it wouldn't be there (as stated in the example).

However, this *is* a caveat. Feel free to add it to the README ☺️

**Comment by florinesueur** [comment]
@manniL Thanks for an answer.
So, I cannot remove unneeded CSS or postCSS in `.vue` ?

**Comment by manniL** [comment]
@florinesueur I think so, yes. At least I wasn't able to do that in `postcss` mode. Might work with `webpack` mode 🤔

**Comment by florinesueur** [comment]
@manniL  Thanks
With the `webpack ` mode, i am obliged to use `extractCSS`.

**Comment by manniL** [comment]
@florinesueur yeah, unfortunately :|

**Comment by florinesueur** [comment]
@manniL Thank you for answering all the questions and for understanding my English. 👍

**Comment by manniL** [comment]
No problem at all ☺️
Your English isn't bad at all :)

If you have more, feel free to join the Nuxt.js Discord (https://discord.nuxtjs.org/) 👍
