### ISSUE TITLE
assets/ ?

### ISSUE THREAD

**Issue by eddiejibson** [Developmint/nuxt-purgecss#40]
Hi,

How would I configure such a module to look through the CSS files in /assets? Or does it do it automatically from what is imported? E.g if it was imported globally via the css key in nuxt config?

**Comment by manniL** [comment]
This kinda defeats the purpose. It should look through your **HTML**/Vue templates instead.

Looking through the CSS files to find unused code would lead to no match, as all the CSS in there, no matter if used or not, is found.
