### ISSUE TITLE
Random scroll behavior issue when reloading the page

### ISSUE THREAD

**Issue by marcfilleul** [Developmint/nuxt-purgecss#46]
Hi,

I share with you the issue and solution I've found:
[https://github.com/sgraewe/create-nuxt-tailwind-app/issues/1](https://github.com/sgraewe/create-nuxt-tailwind-app/issues/1)

Summary:

When using nuxt-purgecss module default settings, the scroll behavior becomes randomly weird when reloading a page.

To avoid this bug, we just need to use postcss mode instead of webpack mode, and to remove Exctract CSS.

**Comment by manniL** [comment]
This is likely more an extractCSS issue than a purgecss one. The functionality should not be different in both modes.
