### ISSUE TITLE
Support for special comments

### ISSUE THREAD

**Issue by gendalf** [Developmint/nuxt-purgecss#48]
Is there are any way to keep analyze special whitelist comments before it will strip?

https://github.com/FullHuman/purgecss-docs/blob/master/whitelisting.md

/* purgecss ignore */

/* purgecss start ignore */

**Comment by manniL** [comment]
This plugin is using purgecss under the hood, so it should be already possible :relaxed:

**Comment by andrewrynhard** [comment]
This doesn't seem to be working as expected. I added `/* purgecss start ignore */` to the top of `main.css` and `/* purgecss end ignore */` to the bottom, but the CSS still never makes it in.

**Comment by danielkellyio** [comment]
I'm having the same issue. Css inside of a /* purgecss start ignore */ and /* purgecss end ignore */ are being purged from production bundle. (When I use `npm run dev` the styles are good, but `npm run generate` results in those styles being missing). Not sure if this is an issue with this moule, nuxt, or some other module I'm using (like maybe the comments are being stripped before it ever gets to purge)??

**Comment by avblink** [comment]
Just confirming, this is still the case

**Comment by avblink** [comment]
In webpack we need to add ! to the comment:

```
/*! purgecss start ignore */
...
/*! purgecss end ignore */
```
But it only works with these comments. not others.

**Comment by manniL** [comment]
Resolved via linked PR
