### ISSUE TITLE
Want to add README.md how to customize extractors

### ISSUE THREAD

**Issue by miyanokomiya** [Developmint/nuxt-purgecss#52]
The only way to override the extractors for each `extensions: ['html', 'vue', 'js']` is a [functional syntax](https://github.com/Developmint/nuxt-purgecss#override-a-default-value).
Because those extensions have been set by default and purgecss uses only one extractor for each extentions.
https://github.com/FullHuman/purgecss/blob/bc9f3b5b9d670832f0d1cca7bc7facfb253fb60b/lib/purgecss.js#L704-L714

This extractor cannot work.
```js
  extractors: [
    { extractor: MyExtracotor1, extensions: ['vue'] }
  ]
```

We must write configs as below to make our extractors work.
```js
  extractors: () => [
    { extractor: MyExtracotor1, extensions: ['vue'] }
  ]
```

**Comment by manniL** [comment]
Go ahead :+1:
