### ISSUE TITLE
Should it be in buildModules and devDependency?

### ISSUE THREAD

**Issue by rchl** [Developmint/nuxt-purgecss#62]
Shouldn't documentation state that it should be added in `buildModules` (or `devModules`) rather than `modules`? And shouldn't it state that this is `devDependency` then? As far as I can see it only affects building.

**Comment by manniL** [comment]
It depends on how you handle devDeps and deps :relaxed: 

Using it in `buildModules` instead of `modules` should be documented, sure.
I'd accept a PR there :relaxed:

**Comment by simllll** [comment]
We have it inside of buildModules and all works fine ;) (and therefore also listed as dev deps)

**Comment by rchl** [comment]
I'm not sure what you meant by this @manniL 
> It depends on how you handle devDeps and deps

**Comment by manniL** [comment]
@rchl 

Some people use devDeps only for linters + testing utils and put "the rest" (so deps needed at build and at run time) in deps.

Others use devDeps for everything build-related and deps only for runtime builds.

**Comment by simplenotezy** [comment]
Would like to know how it can be used in devModules instead 😊 Currently added it to "modules", but not sure what the gains are of adding it to devModules

**Comment by curtisbelt** [comment]
@simplenotezy hey there, `devModules` is actually deprecated in favor of `buildModules`, and you can indeed add it there. The benefit is that `buildModules` are are not loaded in `nuxt start`.

**Comment by simplenotezy** [comment]
Thanks!

**Comment by manniL** [comment]
Will add that in the README. Thanks @rchl
