### ISSUE TITLE
[BUG] Compatibility with purgecss v2

### ISSUE THREAD

**Issue by LuXDAmore** [Developmint/nuxt-purgecss#73]
I've update to the new version of PurgeCSS (v2.0.3) and there is an issue now during the build:
> TypeError: Class constructor extractor cannot be invoked without 'new'

**Comment by LuXDAmore** [comment]
There is an issue opened on the repo of [PurgeCSS](https://github.com/FullHuman/postcss-purgecss/issues/57)

**Comment by LuXDAmore** [comment]
Fixed for me with:
```js
{
    purgeCSS: {
        extractors: () => [
            {
                extractor: content => ( content || '' ).match(
                    /[A-z0-9-:\\/]+/g
                ),
                extensions: [
                    'html',
                    'vue',
                    'js',
                ],
            },
        ],
    },
}
```

**Comment by manniL** [comment]
Upgrading to PurgeCSS 2 should be part of the next major version 👍🏻

**Comment by simllll** [comment]
Just created a PR including a backwards compatible function check, therefore a non breaking change.
