### ISSUE TITLE
ReferenceError: MODES is not defined

### ISSUE THREAD

**Issue by simplenotezy** [Developmint/nuxt-purgecss#78]
I tried installing the library with default advised settings but I am getting:

   ReferenceError: MODES is not defined

This is my config:

	purgeCSS: {
		mode: MODES.webpack,
		enabled: ({ isDev, isClient }) => (!isDev && isClient), // or `false` when in dev/debug mode
		paths: [
			'components/**/*.vue',
			'layouts/**/*.vue',
			'pages/**/*.vue',
			'plugins/**/*.js'
		],
		styleExtensions: ['.css'],
		whitelist: ['body', 'html', 'nuxt-progress'],
		extractors: [
			{
				extractor(content) {
					return content.match(/[A-z0-9-:\\/]+/g)
				},
				extensions: ['html', 'vue', 'js']
			}
		]
	},

**Comment by simplenotezy** [comment]
My build configuration looks like this:

	build: {
		postcss: {
			preset: {
				features: {
					customProperties: false
				}
			}
		},
	}

So I guess I should just change the mode to "postcss"?

**Comment by simplenotezy** [comment]
If I set mode to "postcss", I get error:

		$ export NODE_TLS_REJECT_UNAUTHORIZED=0 && nuxt --env.NODE_TLS_REJECT_UNAUTHORIZED=0
		start Loading module                                                         nuxt-purgecss 12:56:22

		WARN  Module is not enabled                                                 nuxt-purgecss 12:56:22


		FATAL  Missing initializer in const declaration                                           12:56:22

		const consola = require('consola')

		SyntaxError: Missing initializer in const declaration
		at new Script (vm.js:83:7)


		╭───────────────────────────────────────────────────────────╮
		│                                                           │
		│   ✖ Nuxt Fatal Error                                      │
		│                                                           │
		│   SyntaxError: Missing initializer in const declaration   │
		│                                                           │
		╰───────────────────────────────────────────────────────────╯

		error Command failed with exit code 1.

**Comment by manniL** [comment]
`mode: 'webpack'` is fine.

**Comment by simplenotezy** [comment]
By the way @manniL, can you tell me the difference between using postcss and webpack? I'm not quite sure.

**Comment by Khezcute** [comment]
> By the way @manniL, can you tell me the difference between using postcss and webpack? I'm not quite sure.

Plugins r different, u can use fullhuman plugin for postcss without problems also u can change to TailwindCss with this isn't necessary install extra plugins only a extra line in tailwind.config.js
