### ISSUE TITLE
"Module is not enabled" when running Nuxt generate

### ISSUE THREAD

**Issue by simplenotezy** [Developmint/nuxt-purgecss#81]
When running `nuxt generate` I see this warning:

     WARN  Module is not enabled                                                 nuxt-purgecss 14:29:17

Version: ^0.2.1

This is my nuxt.config file:

	purgeCSS: {
		// mode: 'postcss',
		enabled: ({ isDev, isClient }) => (!isDev && isClient), // or `false` when in dev/debug mode
		paths: [
			'components/**/*.vue',
			'layouts/**/*.vue',
			'pages/**/*.vue',
			'plugins/**/*.js'
		],
		styleExtensions: ['.css'],
		whitelist: ['body', 'html', 'nuxt-progress'],
		extractors: [
			{
				extractor(content) {
					return content.match(/[A-z0-9-:\\/]+/g)
				},
				extensions: ['html', 'vue', 'js']
			}
		]
	},

**Comment by manniL** [comment]
1. Please provide a reproduction (repo/codesandbox)
2. I highly recommend **not** copy-pasting the default config values. Instead, only alter the values you really want to change. That makes debugging easier.

**Comment by simplenotezy** [comment]
Well, seems like if I remove the default configuration as you said, it doesn't show this error. Initially when setting it up, it seemed like I needed to add it.

I'll keep you posted if I see more errors.

**Comment by manniL** [comment]
Stale
