### ISSUE TITLE
regex doesn't work in the whitelist option

### ISSUE THREAD

**Issue by ms-fadaei** [Developmint/nuxt-purgecss#99]
When I use regex in the whitelist option, the PurgeCSS still removed those rules

```js
whitelist:  [/^simplebar-.*$/],
```

**Comment by ms-fadaei** [comment]
I realize that I must use `whitelistPatterns` instead of `whitelist`

**Comment by curtisbelt** [comment]
I believe you have to use `whitelistPatterns` instead of `whitelist` in order to use regex.
See the PurgeCSS 2.x docs for whistlisting patterns here: https://github.com/FullHuman/purgecss/blob/5314e41edf328e2ad2639549e1587b82a964a42e/docs/whitelisting.md#patterns

**Comment by curtisbelt** [comment]
Oh, you got it already! 😆
